apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectbolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectbolt  # ✅ Must match service selector
  template:
    metadata:
      labels:
        app: projectbolt  # ✅ Must match deployment selector
    spec:
      containers:
      - name: projectbolt-container
        image: projectbolt:1.0
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: projectbolt-service
spec:
  selector:
    app: projectbolt  # ✅ Must match Deployment selector
  ports:
  - protocol: TCP
    port: 80  # ✅ Exposes the app externally
    targetPort: 5173  # ✅ Must match containerPort
  type: NodePort
